### ISSUE TITLE
Incorrect "to" version in commit message when new version exists within constraints

### ISSUE THREAD

**Issue by monfresh** [lpender/bummr#14]
If you have a version constraint in the Gemfile, such as `gem 'devise', '~> 3.4'`, and if there is a new version available that is within the constraints, the commit message includes extra text that refers to the constraint, such as:

```
Update devise from 3.5.6, requested ~> 3.4 to 3.5.10
```

**Comment by lpender** [comment]
Do you have the message from `bundle outdated --list` that created that issue?

For example:

`* devise (newest 3.5.10, installed 3.5.6, requested ~> 3.4)`

I'd like to write a test that simulates the correct input.

Thanks

**Comment by monfresh** [comment]
I don't, but I think this is probably what it was:

```
* devise (newest 3.5.10, installed 3.5.6, requested ~> 3.4) in group "default"
```

**Comment by monfresh** [comment]
Here's another example that failed:

```
* faraday-http-cache (newest 1.3.0, installed 1.2.2, requested ~> 1.0) in group "default"
```

**Comment by lpender** [comment]
Ok, I have a fix

**Comment by lpender** [comment]
https://github.com/lpender/bummr/pull/16
