### ISSUE TITLE
Gem does not get updated if current version has more than 3 digits

### ISSUE THREAD

**Issue by monfresh** [lpender/bummr#15]
For example, I had Rails 4.2.5.1, but it did not get updated to 4.2.6:

```
rails not updated from 4.2.5.1, requested ~> 4.2.0 to latest: 4.2.6
```

**Comment by monfresh** [comment]
Output from `bundle outdated`:

```
* rails (newest 4.2.6, installed 4.2.5.1, requested ~> 4.2.0) in group "default"
```

**Comment by lpender** [comment]
Is it perhaps locked in your Gemfile?

**Comment by lpender** [comment]
I'm not sure why this would be, I don't think it has to do with the 4 digits. 

The command I'm running behind the scenes is:

`bundle update --source rails`

**Comment by monfresh** [comment]
I'm pretty sure it was the regex that was an issue. If you enter the old regex in rubular.com:

```
 \* (.*) \(newest (\d.*\d), installed (\d.*\d)[\),\s]
```

and test against this string:

```
* rails (newest 4.2.6, installed 4.2.5.1, requested ~> 4.2.0) in group "default"
```

it won't find any matches

**Comment by monfresh** [comment]
Same with the latest regex

**Comment by monfresh** [comment]
My bad. I had an extra space at the beginning. Seems like rubular.com doesn't like that. Is the leading space necessary in the gem?

**Comment by monfresh** [comment]
also, `bundle update rails` worked for me. I didn't try with the `--source` flag.

**Comment by lpender** [comment]
Here's my inspiration for using the `--source` flag. 

http://ilikestuffblog.com/2012/07/01/you-should-update-one-gem-at-a-time-with-bundler-heres-how/

It doesn't appear to be very well understood, but it seems to use a more conservative update strategy.

I'm open to removing the flag

**Comment by monfresh** [comment]
Hmm. From the documentation, I don't see how it's more conservative. It seems to only apply when you have a `git` or `path` source specified in the gemfile. But even then, I've always used `bundle update` without any flags, and the `git` or `path` sources were always updated.

I can try to reproduce again to see if it's the `source` flag that's causing the issue.

**Comment by lpender** [comment]
Read the article as well as the documentation.

**Comment by monfresh** [comment]
I read the article, but I'm not convinced. It's 4 years old. A lot could have changed since then. From reading the Bundler specs, it doesn't look the source option does anything special besides using the source specified in the Gemfile:

https://github.com/bundler/bundler/blob/dfdeb0f89e7e88fcdfd001da089f09af3a77d2b4/spec/update/path_spec.rb

https://github.com/bundler/bundler/blob/dfdeb0f89e7e88fcdfd001da089f09af3a77d2b4/spec/update/git_spec.rb#L40-L57

**Comment by lpender** [comment]
https://github.com/lpender/bummr/pull/27

**Comment by lpender** [comment]
@monfresh I removed the `--source` flag in `0.1.3`
