### ISSUE TITLE
Commit message incorrect version

### ISSUE THREAD

**Issue by map7** [lpender/bummr#2]
In my Gemfile I've locked down a lot of my gems to minor updates only, when running your `bummr update` command the commit message includes the most recent version of that gem instead of the version bummr updated that gem to.

eg: 
For the paperclip gem I have the following in my Gemfile

```
gem 'paperclip', '~> 3.0'
```

When bummr updates it it takes it from 3.4.1 to 3.5.4, which is good, but it makes the commit message;

```
paperclip, {3.4.1 -> 4.3.6} 
```

This is incorrect.

**Comment by lpender** [comment]
Thanks for the report, I'll take a look

**Comment by lpender** [comment]
Fixed in 0.0.6
