### ISSUE TITLE
bummr test does not properly assign bisect bad and continue

### ISSUE THREAD

**Issue by map7** [lpender/bummr#3]
I'm not sure if I'm using this correctly but after it ran for a long time doing it's update with 'bummr update' it stopped as it found some untracked files in my branch (because I cache the gems in vendor/cache). So I had to start 'bummr test' manually. I thought this would run tests and bisect bad/good depending if they passed and go to the next commit, is this correct?

The problem I'm having is when I run bummr test it runs my tests and 4 fail out of 906 and then it displays the following and stops on the terminal

```
Ready to run bummr.
Bad commits found! Bisecting...
You need to give me at least one good and one bad revisions.
(You can use "git bisect bad" and "git bisect good" for that.)
```

Then I have to manually 'git bisect bad', now do I run bummr test again here or is this something bummr should be doing automatically?

**Comment by lpender** [comment]
What does a `git status` tell you?

I'm guessing it exited 'bisect' in a strange state, and you have to `git bisect reset`.

You have a `.bummr-build.sh` file committed to master?

Thanks,
-L

**Comment by map7** [comment]
I get the following

```
% git status     
# On branch gemupdate
# You are currently bisecting, started from branch 'gemupdate'.
#   (use "git bisect reset" to get back to the original branch)
#
nothing to commit, working directory clean
```

I have got my .bummr-build.sh file commited in master with the following

```
#!/bin/sh
bundle exec rake
```

**Comment by lpender** [comment]
I'm guessing you started the test command when you were already in a state of `bisecting`. Sometimes the automatic removal of the bad sha fails for some reason, and it needs to be removed manually, and then you need to `git rebase --cont`. I'm working on some updates today that will hopefully make this easier to detect.

**Comment by lpender** [comment]
I added some tests in `0.0.6` that will prevent you from starting `bummr` if your `git status` is complicated. Please update and try again if you like.

Thanks for the report.

**Comment by map7** [comment]
I just updated to the latest bummr and still have this issue.

```
Ready to run bummr.
Bad commits found! Bisecting...
You need to give me at least one good and one bad revisions.
(You can use "git bisect bad" and "git bisect good" for that.)
```

I run the following as suggested but nothing happens;

```
 (gemupdate)% g bisect bad
 (gemupdate)% g rebase --cont
No rebase in progress?

 (gemupdate)% g s
# On branch gemupdate
# You are currently bisecting, started from branch 'gemupdate'.
#   (use "git bisect reset" to get back to the original branch)
#
nothing to commit, working directory clean
```

**Comment by lpender** [comment]
Try `git bisect reset` and then starting over?

**Comment by map7** [comment]
I've already doing a reset, same problem

```
g bisect reset
bummr test
```

**Comment by lpender** [comment]
You might want to clone the repo and do some debugging locally--it's very hard for me to know from here.

There are instructions in the README under "Developing"

**Comment by lpender** [comment]
I think I may, in fact, have a fix. Standby

**Comment by lpender** [comment]
What is the output of `git bisect start head master`? This is the last command run before you get that message, it should tell git bisect the good and bad revisions

**Comment by map7** [comment]
I can run bisect manually and run my tests manually

```
git bisect start
git bisect bad
git bisect good master
```

Then just marking my good/bad commits. This works.

If I use `git bisect start head master` that doesn't mark my commits good & bad. I think it's because I'm using an old version of git (1.9.1).

**Comment by lpender** [comment]
I think yes, that must be it.

Feel free to submit a PR or I can take a look later today.

Thanks
Lee

**Comment by map7** [comment]
Cool, I've forked the project and proved my theory, it is that one command and it works if I do the three separate system commands. I'll send through a PR

**Comment by lpender** [comment]
Great, thanks

**Comment by lpender** [comment]
Release in `0.1.4`
