### ISSUE TITLE
Consider using rainbow instead of colorize due to GPL license restriction

### ISSUE THREAD

**Issue by monfresh** [lpender/bummr#32]
Hi @lpender, I started looking into license compliance for some projects I'm working on, and we can't use a gem that uses the GPL license without our project changing its license to GPL, which we don't want to do. The `colorize` gem uses the GPL-2 license, and the owner of the project doesn't seem to want to change it. See this issue: https://github.com/fazibear/colorize/issues/47

In that thread, someone recommended the [rainbow](https://github.com/sickill/rainbow) gem, which seems like a good alternative. Would you consider switching to rainbow?

I noticed that you use the MIT license for `bummr`, but because you use `colorize`, you would need to convert to a GPL-2 license, which is probably not what you want.

**Comment by lpender** [comment]
Hey there.

Would you like to open a pull request for the changes you mentioned?

Thanks
Lee

**Comment by monfresh** [comment]
Sure, I can give it a shot, but it will probably take me more time than you since I haven't used colorize or rainbow before. Also, is the dependency on colorize covered in the test suite? How would I know whether or not the switch from colorize to rainbow didn't break anything?

**Comment by monfresh** [comment]
Do I just need to look for methods like `.red`, `.green`, `.yellow` and check the output manually?

**Comment by connorshea** [comment]
@monfresh this might help as an example: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/4425

**Comment by skull-squadron** [comment]
Just ran into this myself. Awesome license checker tool:   `gem install license_finder` [github](https://github.com/pivotal/LicenseFinder)

**Comment by lpender** [comment]
Fixed in `0.1.6`. Thx

**Comment by monfresh** [comment]
Thanks!
