### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by balki-server** [lpender/bummr#37]
Hello there
You don't have a license on this repo which might scare away most folks from adopting/incorporating.  A license like [MIT](https://github.com/bundler/bundler/blob/master/LICENSE.md) is probably sufficient for this repo.

Best
Balki
http://www.balki.io

**Comment by lpender** [comment]
`spec.license` shows "MIT" but I can add it to the README as well.

Thanks
-Lee

**Comment by lpender** [comment]
Done.

https://github.com/lpender/bummr/commit/d9f0e89f7d9822aab50a9942b3b520c78680adb3

**Comment by balki-server** [comment]
awesome thx @lpender
