### ISSUE TITLE
Yank 0.2.0?

### ISSUE THREAD

**Issue by odlp** [lpender/bummr#42]
Thanks for merging #41 so quickly & cutting the `0.1.8` release. I noticed on the [`bummr` versions listed on Rubygems](https://rubygems.org/gems/bummr/versions) that `0.2.0` was released (accidentally?) in March?

Currently when one runs `gem install bummr` you get:

```
Fetching: bummr-0.2.0.gem (100%)
Successfully installed bummr-0.2.0
1 gem installed
```

Which isn't actually the latest code. It might be worth yanking `0.2.0` - or skipping ahead `0.3.0`?

**Comment by lpender** [comment]
Hmm... Not sure how that happened! I've yanked `0.2.0`.

Please give it another shot! Thanks!

**Comment by odlp** [comment]
👍  `gem install bummr` now provides `0.1.8`
