### ISSUE TITLE
Add vendor/cache directory

### ISSUE THREAD

**Issue by map7** [lpender/bummr#56]
For my project I keep a vendor/cache directory just incase rubygems goes down and bummr doesn't play nicely with this directory as it doesn't add it to git when committing. I propose that the following line be changed to include the vendor/cache directory when committing changes.

https://github.com/lpender/bummr/blob/7f10a29797111d6a0464d3f520dace4e06d20b23/lib/bummr/updater.rb#L39

**Comment by map7** [comment]
I propose something like this;
`system("git add Gemfile Gemfile.lock vendor/cache") `

**Comment by lpender** [comment]
This is fixed, thanks
