### ISSUE TITLE
is Rails itself excluded, to allow interative 4.2, 5.0, 5.1, 5.2 upgrading?

### ISSUE THREAD

**Issue by jpwynn** [lpender/bummr#62]
Starting a 4.2 -> 5.0 -> 5.1 -> 5.2 upgrade sequence, I was looking at bummr as a way to get the current non-rails gems updated prior to the jump to the next version.

Does/can bummr exclude Rails itself from the upgrade process, to support a .X at a time upgrade workflow?

**Comment by s01ipsist** [comment]
You could just pin the gems you don't want to move.
```
gem 'rails', '4.2.11.3'
```
