### ISSUE TITLE
Some version numbers in commit message are wrong

### ISSUE THREAD

**Issue by monfresh** [lpender/bummr#8]
For example, I have the following commit messages:

Update redis from 3.2.2 to 0.6.1
Update sass from 3.4.21 to 3.3.6

The `to` version number should be higher but it's lower in these cases.

**Comment by monfresh** [comment]
This is due to the way the updated version is being parsed:

``` ruby
updated_version = `bundle list | grep #{gem[:name]}`.split('(')[1].split(')')[0]
```

You are relying on grep, which is not enough because grepping for `sass` will also find a match in `bootstrap-sass`, which is where it got `3.3.6` in my case.

**Comment by lpender** [comment]
Ah, thanks for the report and the debugging. I'm going to do some improvements to that regex now and release 0.0.7.

**Comment by lpender** [comment]
https://github.com/lpender/bummr/pull/9
